In [2]:
import pandas as pd

df = pd.read_csv("../data/customer_churn_business_dataset_cleaned.csv")
df.shape

(10000, 35)

In [3]:
df["churn"].mean()

np.float64(0.1021)

In [5]:
df["tenure_group"]=pd.cut(
    df["tenure_months"],
    bins=[0,6,12,24,48,60],
    labels=["0-6 months", "7-12 months", "1-2 years", "2-4 years", "4-5 years"]
)

df[["tenure_months", "tenure_group"]].head(10)

   tenure_months tenure_group
0             22    1-2 years
1              9  7-12 months
2             58    4-5 years
3             19    1-2 years
4             52    4-5 years
5             54    4-5 years
6             54    4-5 years
7              7  7-12 months
8             15    1-2 years
9             17    1-2 years

In [6]:
df.groupby("tenure_group", observed=True)["churn"].agg(["mean", "count"])

                  mean  count
tenure_group
0-6 months    0.281008   1032
7-12 months   0.088409   1018
1-2 years     0.087569   1987
2-4 years     0.076866   4059
4-5 years     0.081408   1904

In [7]:
df.groupby("csat_score")["churn"].agg(["mean", "count"])

                mean  count
csat_score
1.0         0.235294    221
2.0         0.260212   1322
3.0         0.079290   3380
4.0         0.067272   3523
5.0         0.077220   1554

In [8]:
df.groupby("payment_failures")["churn"].agg(["mean", "count"])

                      mean  count
payment_failures
0                 0.087607   6084
1                 0.086651   2989
2                 0.252564    780
3                 0.215385    130
4                 0.214286     14
5                 0.333333      3

In [10]:
df["failures_2plus"] = df["payment_failures"] >= 2

df.groupby("failures_2plus")["churn"].agg(["mean", "count"])

                    mean  count
failures_2plus
False           0.087292   9073
True            0.247033    927

In [12]:
df["login_group"]=pd.qcut(df["monthly_logins"],4)

df.groupby("login_group", observed=True)["churn"].agg(["mean","count"])

                    mean  count
login_group
(-0.001, 13.0]  0.143118   2739
(13.0, 20.0]    0.090318   2613
(20.0, 26.0]    0.089082   2189
(26.0, 54.0]    0.080521   2459

In [13]:
df.groupby(pd.cut(df["monthly_logins"], 4), observed=True)["churn"].agg(["mean", "count"])

                    mean  count
monthly_logins
(-0.054, 13.5]  0.143118   2739
(13.5, 27.0]    0.090338   5092
(27.0, 40.5]    0.076845   1978
(40.5, 54.0]    0.089005    191

In [14]:
churned = df[df["churn"] ==1]
churned["monthly_fee"].sum()

np.int64(35300)

In [15]:
churned["monthly_fee"].sum()/df["monthly_fee"].sum()

np.float64(0.10105926137990266)

In [16]:
df.groupby(
    pd.cut(df["last_login_days_ago"], bins=[-1, 7, 14, 30, 80]),
    observed=True
)["churn"].agg(["mean", "count"])

                         mean  count
last_login_days_ago
(-1, 7]              0.099453   5480
(7, 14]              0.098368   2328
(14, 30]             0.092865   1766
(30, 80]             0.194836    426